freedom-mod-development-community/asta-all-config-syncer:
  deployment:
    props:
      - ACTIONS_PAT

anatawa12/auto-tostring:
  deployment:
    props:
      - ACTIONS_PAT
      - GPG_PRIVATE_KEY
      - GPG_PRIVATE_PASS
      - SONATYPE_USER
      - SONATYPE_PASS
      - GRADLE_KEY
      - GRADLE_SECRET

anatawa12/auto-visitor:
  deployment:
    props:
      - ACTIONS_PAT
      - GPG_PRIVATE_KEY
      - GPG_PRIVATE_PASS
      - SONATYPE_USER
      - SONATYPE_PASS
      - GRADLE_KEY
      - GRADLE_SECRET
      - INTELLIJ_TOKEN

anatawa12/compile-time-constant:
  deployment:
    props:
      - ACTIONS_PAT
      - GPG_PRIVATE_KEY
      - GPG_PRIVATE_PASS
      - GRADLE_KEY
      - GRADLE_SECRET
      - SONATYPE_PASS
      - SONATYPE_USER

anatawa12/game-save-backuper:
  deployment:
    props:
      - ACTIONS_PAT
      - CRATES_IO_TOKEN


anatawa12/github-features-test:
  deployment:
    props:
      - ACTIONS_PAT

fixrtm/jar-in-jar-mod:
  deployment:
    props:
      - ACTIONS_PAT
      - GPG_PRIVATE_KEY
      - GPG_PRIVATE_PASS
      - GRADLE_KEY
      - GRADLE_SECRET
      - SONATYPE_PASS
      - SONATYPE_USER

anatawa12/mod-downloader:
  deployment:
    props:
      - ACTIONS_PAT

fixrtm/mod-patching:
  deployment:
    props:
      - ACTIONS_PAT
      - GPG_PRIVATE_KEY
      - GPG_PRIVATE_PASS
      - GRADLE_KEY
      - GRADLE_SECRET
      - SONATYPE_PASS
      - SONATYPE_USER

anatawa12/something-releaser:
  deployment:
    props:
      - ACTIONS_PAT

anatawa12/zip-http-server:
  deployment:
    props:
      - ACTIONS_PAT
      - CRATES_IO_TOKEN

anatawa12/discord-rcon:
  deployment:
    props:
      - ACTIONS_PAT
      - CRATES_IO_TOKEN

fixrtm/plugin-permissions-for-ngt:
  deployment:
    props:
      - ACTIONS_PAT

anatawa12/ForgeGradle-1.2:
  deployment:
    props:
      - ACTIONS_PAT
      - GPG_PRIVATE_KEY
      - GPG_PRIVATE_PASS
      - SONATYPE_PASS
      - SONATYPE_USER

anatawa12/ForgeGradle-2.3:
  deployment:
    props:
      - ACTIONS_PAT
      - GPG_PRIVATE_KEY
      - GPG_PRIVATE_PASS
      - SONATYPE_PASS
      - SONATYPE_USER
