name: Ci

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch: { }

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - uses: Swatinem/rust-cache@v1
        with:
          target-dir: target

      - name: Build
        run: cargo build
